[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer = "6usCzh8XM4LPL45zWkkPALz7jFCM4ojhhE5sjBTAW5JD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
